package com.example.nikola.waterreport.model;

/**
 * Quality/Purity report information holder.
 *
 * Created by Nikola Istvanic.
 */
public class QualityReport {
    private String userName;
    private String time;
    private int id;
    private String location;
    private String condition;
    private double virusPPM;
    private double contaminantPPM;
    private double lat;
    private double lng;

    /**
     * No arg constructor (for Firebase)
     */
    public QualityReport() {}

    /**
     * Constructor for QualityReport object
     * @param userName Username of user who created this QualityReport
     * @param time Time autogenerated whenever this QualityReport was created
     * @param id ID autogenerated whenever this QualityReport was created
     * @param location Location entered by the user upon creation
     * @param condition Condition chosen by the user
     * @param virusPPM virus PPM double
     * @param contaminantPPM contamination PPM double
     * @param lat QualityReport latitude
     * @param lng QualityReport longitude
     */
    public QualityReport(String userName, String time, int id, String location, String condition,
                         double virusPPM, double contaminantPPM, double lat, double lng) {
        this.userName = userName;
        this.time = time;
        this.id = id;
        this.location = location;
        this.condition = condition;
        this.virusPPM = virusPPM;
        this.contaminantPPM = contaminantPPM;
        this.lat = lat;
        this.lng = lng;
    }

    /**
     * Getter for userName
     * @return Username of the user who created this QualityReport
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Location user entered whenever creating this QualityReport
     * @return location private data
     */
    public String getLocation() {
        return location;
    }

    /**
     * Getter for the time autogenerated when this QualityReport was created
     * @return time private data
     */
    public String getTime() {
        return time;
    }

    /**
     * Getter for the ID of this QualityReport
     * @return ID autogenerated whenever this QualityReport was created
     */
    public int getId() {
        return id;
    }

    /**
     * Getter for condition
     * @return String representation of the source
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Getter for virusPPM.
     * @return virusPPM
     */
    public double getVirusPPM() {
        return virusPPM;
    }

    /**
     * Getter for contaminantPPM.
     * @return contaminantPPM
     */
    public double getContaminantPPM() {
        return contaminantPPM;
    }

    /**
     * Getter for latitude
     * @return latitude for this WaterReport
     */
    public double getLat() {
        return lat;
    }

    /**
     * Getter for longitude
     * @return longitude for this WaterReport
     */
    public double getLng() {
        return lng;
    }

    /**
     * Equality of QualityReports is determined by location and virus/contaminant PPM.
     * @param a The object that you are comparing it to
     * @return true if the id of the object is equal to this objects id, false otherwise
     */
    @Override
    public boolean equals(Object a) {
        if (a == null || !(a instanceof QualityReport)) {
            return false;
        }
        if (this == a) {
            return true;
        }
        QualityReport that = (QualityReport) a;
        return getLat() == that.getLat() && getLng() == that.getLng()
                && getVirusPPM() == that.getVirusPPM()
                && getContaminantPPM() == that.getContaminantPPM();
    }

    /**
     * String representation of QualityReport
     * @return QualityReport as a String with all metadata listed
     */
    @Override
    public String toString() {
        return "ID: " + id + "\nCreated on " + time + "\nCreated by " + userName + "\nSource: "
                + "\nCondition: " + condition + "\nLocation: " + location
                + "\nVirus PPM: " + virusPPM + "\nContaminant PPM: " + contaminantPPM
                + "\nLatitude: " + lat + "\nLongitude: " + lng + "\n\n";
    }
}
