package com.example.nikola.waterreport.model;

/**
 * Created by Prithviraj Ammanabrolu.
 */
public class WaterReport {
    private String userName;
    private String time;
    private int id;
    private String location;
    private String source;
    private String condition;

    /**
     * Constructor for WaterReport object
     * @param userName Username of user who created this WaterReport
     * @param time Time autogenerated whenever this WaterReport was created
     * @param id ID autogenerated whenever this  WaterReport was created
     * @param location Location entered by the user upon creation
     * @param source Source chosen by the user
     * @param conditon Condition chosen by the user
     */
    public WaterReport(String userName, String time, int id, String location, String source, String conditon) {
        this.userName = userName;
        this.time = time;
        this.id = id;
        this.location = location;
        this.source = source;
        this.condition = conditon;
    }

    /**
     * Getter for userName
     * @return Username of the user who created this WaterReport
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Location user entered whenever creating this WaterReport
     * @return location private data
     */
    public String getLocation() {
        return location;
    }

    /**
     * Getter for the time autogenerated when this WaterReport was created
     * @return time private data
     */
    public String getTime() {
        return time;
    }

    /**
     * Getter for the ID of this WaterReport
     * @return ID autogenerated whenever this WaterReport was created
     */
    public int getId() {
        return id;
    }

    /**
     * Getter for source
     * @return String representation of the source
     */
    public String getSource() {
        return source;
    }

    /**
     * Getter for condition
     * @return String representation of the source
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Equality of WaterReports is determined by ID.
     * @param a The object that you are comparing it to
     * @return true if the id of the object is equal to this objects id, false otherwise
     */
    @Override
    public boolean equals(Object a) {
        if (a == null || !(a instanceof WaterReport)) {
            return false;
        }
        if (this == a) {
            return true;
        }
        WaterReport that = (WaterReport) a;
        return id == that.id;
    }

    /**
     * String representation of WaterReport
     * @return WaterReport as a String with all metadata listed
     */
    @Override
    public String toString() {
        return "ID: " + id + "\nCreated on: " + time + "\nCreated by: " + userName + "\nSource: " + source + "\nCondition: " + condition + "\nLocation: " + location + "\n\n";
    }
}
