DROP SCHEMA IF EXISTS DB;
CREATE SCHEMA DB;

USE DB;

DROP TABLE IF EXISTS Accounts;

CREATE TABLE Accounts (
    ID          VARCHAR(120)    NOT NULL UNIQUE,
	USR			VARCHAR(120)	NOT NULL,
    PASS	    VARCHAR(120)   	NOT NULL,
    TYPE        CHAR(7)         NOT NULL,
	PRIMARY KEY (USR)
);
